package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountHasGroupId generated by hbm
 */
@Embeddable
public class AccountHasGroupId  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYGROUPID = "AccountHasGroupId.findByGroupId";
        public static final String FINDBYACCOUNTID = "AccountHasGroupId.findByAccountId";
    }




     private int groupId;
     private int accountId;

    public AccountHasGroupId() {


        //

        //

    }

    public AccountHasGroupId(int groupId, int accountId) {
       this.groupId = groupId;
       this.accountId = accountId;
    }
   

    @Column(name="group_id", nullable=false)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    @Column(name="account_id", nullable=false)
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AccountHasGroupId) ) return false;
		 AccountHasGroupId castOther = ( AccountHasGroupId ) other; 
         
		 return (this.getGroupId()==castOther.getGroupId())
 && (this.getAccountId()==castOther.getAccountId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGroupId();
         result = 37 * result + this.getAccountId();
         return result;
   }   



}
