package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AccountMeta generated by hbm
 */
@Entity
@EntityListeners(value={
AccountMeta.LastUpdateListener.class,
AccountMeta.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="AccountMeta")
@NamedQueries({
@NamedQuery(name = "AccountMeta.findAll", query = "SELECT n FROM AccountMeta n"),
@NamedQuery(name = "AccountMeta.findByAccount", query = "SELECT n FROM AccountMeta n WHERE n.account = :account"),
@NamedQuery(name = "AccountMeta.findByUid", query = "SELECT n FROM AccountMeta n WHERE n.uid = :uid"),
@NamedQuery(name = "AccountMeta.findByCreated", query = "SELECT n FROM AccountMeta n WHERE n.created = :created"),
@NamedQuery(name = "AccountMeta.findByModified", query = "SELECT n FROM AccountMeta n WHERE n.modified = :modified"),
@NamedQuery(name = "AccountMeta.findByMwrench", query = "SELECT n FROM AccountMeta n WHERE n.mwrench = :mwrench"),
@NamedQuery(name = "AccountMeta.findByMvalue", query = "SELECT n FROM AccountMeta n WHERE n.mvalue = :mvalue"),
})
@Table(name="account_meta"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class AccountMeta  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "AccountMeta.findById";
        public static final String FINDBYACCOUNT = "AccountMeta.findByAccount";
        public static final String FINDBYUID = "AccountMeta.findByUid";
        public static final String FINDBYCREATED = "AccountMeta.findByCreated";
        public static final String FINDBYMODIFIED = "AccountMeta.findByModified";
        public static final String FINDBYMWRENCH = "AccountMeta.findByMwrench";
        public static final String FINDBYMVALUE = "AccountMeta.findByMvalue";
    }




     private AccountMetaId id;
     private Account account;
     private String uid;
     private Date created;
     private Date modified;
     private String mwrench;
     private String mvalue;

    public AccountMeta() {


        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

    }

    public AccountMeta(AccountMetaId id, Account account, String uid, Date created, Date modified, String mwrench, String mvalue) {
       this.id = id;
       this.account = account;
       this.uid = uid;
       this.created = created;
       this.modified = modified;
       this.mwrench = mwrench;
       this.mvalue = mvalue;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="accountId", column=@Column(name="account_id", nullable=false) ) } )
    public AccountMetaId getId() {
        return this.id;
    }
    
    public void setId(AccountMetaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id", nullable=false, insertable=false, updatable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    
    @Column(name="uid", unique=true, nullable=false)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="mwrench", nullable=false)
    public String getMwrench() {
        return this.mwrench;
    }
    
    public void setMwrench(String mwrench) {
        this.mwrench = mwrench;
    }
    
    @Column(name="mvalue", nullable=false, length=65535)
    public String getMvalue() {
        return this.mvalue;
    }
    
    public void setMvalue(String mvalue) {
        this.mvalue = mvalue;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(AccountMeta o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(AccountMeta o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
