package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AccountImage generated by hbm
 */
@Entity
@EntityListeners(value={
AccountImage.LastUpdateListener.class,
AccountImage.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="AccountImage")
@NamedQueries({
@NamedQuery(name = "AccountImage.findAll", query = "SELECT n FROM AccountImage n"),
@NamedQuery(name = "AccountImage.findByAccount", query = "SELECT n FROM AccountImage n WHERE n.account = :account"),
@NamedQuery(name = "AccountImage.findByUid", query = "SELECT n FROM AccountImage n WHERE n.uid = :uid"),
@NamedQuery(name = "AccountImage.findByCreated", query = "SELECT n FROM AccountImage n WHERE n.created = :created"),
@NamedQuery(name = "AccountImage.findByModified", query = "SELECT n FROM AccountImage n WHERE n.modified = :modified"),
@NamedQuery(name = "AccountImage.findByTaxonomy", query = "SELECT n FROM AccountImage n WHERE n.taxonomy = :taxonomy"),
@NamedQuery(name = "AccountImage.findByImage", query = "SELECT n FROM AccountImage n WHERE n.image = :image"),
})
@Table(name="account_image"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class AccountImage  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "AccountImage.findById";
        public static final String FINDBYACCOUNT = "AccountImage.findByAccount";
        public static final String FINDBYUID = "AccountImage.findByUid";
        public static final String FINDBYCREATED = "AccountImage.findByCreated";
        public static final String FINDBYMODIFIED = "AccountImage.findByModified";
        public static final String FINDBYTAXONOMY = "AccountImage.findByTaxonomy";
        public static final String FINDBYIMAGE = "AccountImage.findByImage";
    }




     private Integer id;
     private Account account;
     private String uid;
     private Date created;
     private Date modified;
     private String taxonomy;
     private String image;

    public AccountImage() {


        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

    }

    public AccountImage(Account account, String uid, Date created, Date modified, String taxonomy, String image) {
       this.account = account;
       this.uid = uid;
       this.created = created;
       this.modified = modified;
       this.taxonomy = taxonomy;
       this.image = image;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id", nullable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    
    @Column(name="uid", unique=true, nullable=false)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="taxonomy", nullable=false, length=20)
    public String getTaxonomy() {
        return this.taxonomy;
    }
    
    public void setTaxonomy(String taxonomy) {
        this.taxonomy = taxonomy;
    }
    
    @Column(name="image", nullable=false)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(AccountImage o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(AccountImage o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
