package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Booking generated by hbm
 */
@Entity
@EntityListeners(value={
Booking.LastUpdateListener.class,
Booking.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="Booking")
@NamedQueries({
@NamedQuery(name = "Booking.findAll", query = "SELECT n FROM Booking n"),
@NamedQuery(name = "Booking.findByUid", query = "SELECT n FROM Booking n WHERE n.uid = :uid"),
@NamedQuery(name = "Booking.findByCreated", query = "SELECT n FROM Booking n WHERE n.created = :created"),
@NamedQuery(name = "Booking.findByModified", query = "SELECT n FROM Booking n WHERE n.modified = :modified"),
@NamedQuery(name = "Booking.findByVisible", query = "SELECT n FROM Booking n WHERE n.visible = :visible"),
@NamedQuery(name = "Booking.findByStatus", query = "SELECT n FROM Booking n WHERE n.status = :status"),
@NamedQuery(name = "Booking.findByWithTicket", query = "SELECT n FROM Booking n WHERE n.withTicket = :withTicket"),
})
@Table(name="booking"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class Booking  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "Booking.findById";
        public static final String FINDBYUID = "Booking.findByUid";
        public static final String FINDBYCREATED = "Booking.findByCreated";
        public static final String FINDBYMODIFIED = "Booking.findByModified";
        public static final String FINDBYVISIBLE = "Booking.findByVisible";
        public static final String FINDBYSTATUS = "Booking.findByStatus";
        public static final String FINDBYWITHTICKET = "Booking.findByWithTicket";
    }




     private Integer id;
     private String uid;
     private Date created;
     private Date modified;
     private Boolean visible;
     private String status;
     private Boolean withTicket;
     private List<EventHasBooking> eventHasBookings = new ArrayList<EventHasBooking>(0);

    public Booking() {


        //

        //
        //this.setUid(TokenUtils.generateUid());
        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //

        //

    }

	
    public Booking(String uid, Date created, Date modified) {
        this.uid = uid;
        this.created = created;
        this.modified = modified;
    }
    public Booking(String uid, Date created, Date modified, Boolean visible, String status, Boolean withTicket, List<EventHasBooking> eventHasBookings) {
       this.uid = uid;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
       this.status = status;
       this.withTicket = withTicket;
       this.eventHasBookings = eventHasBookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="uid", unique=true, nullable=false)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="with_ticket")
    public Boolean getWithTicket() {
        return this.withTicket;
    }
    
    public void setWithTicket(Boolean withTicket) {
        this.withTicket = withTicket;
    }
   @OneToMany(fetch=FetchType.LAZY, mappedBy="booking")
   @Cascade(value=CascadeType.ALL)                    
   @Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="Booking.EventHasBookings")
   @Fetch(value=FetchMode.SUBSELECT)                    
    public List<EventHasBooking> getEventHasBookings() {
        return this.eventHasBookings;
    }
    
    public void setEventHasBookings(List<EventHasBooking> eventHasBookings) {
        this.eventHasBookings = eventHasBookings;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(Booking o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(Booking o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
