package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Bundle generated by hbm
 */
@Entity
@EntityListeners(value={
Bundle.LastUpdateListener.class,
Bundle.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="Bundle")
@NamedQueries({
@NamedQuery(name = "Bundle.findAll", query = "SELECT n FROM Bundle n"),
@NamedQuery(name = "Bundle.findByUid", query = "SELECT n FROM Bundle n WHERE n.uid = :uid"),
@NamedQuery(name = "Bundle.findByStatus", query = "SELECT n FROM Bundle n WHERE n.status = :status"),
@NamedQuery(name = "Bundle.findByVisible", query = "SELECT n FROM Bundle n WHERE n.visible = :visible"),
@NamedQuery(name = "Bundle.findByCreated", query = "SELECT n FROM Bundle n WHERE n.created = :created"),
@NamedQuery(name = "Bundle.findByModified", query = "SELECT n FROM Bundle n WHERE n.modified = :modified"),
})
@Table(name="bundle"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class Bundle  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "Bundle.findById";
        public static final String FINDBYUID = "Bundle.findByUid";
        public static final String FINDBYSTATUS = "Bundle.findByStatus";
        public static final String FINDBYVISIBLE = "Bundle.findByVisible";
        public static final String FINDBYCREATED = "Bundle.findByCreated";
        public static final String FINDBYMODIFIED = "Bundle.findByModified";
    }




     private Integer id;
     private String uid;
     private String status;
     private Boolean visible;
     private Date created;
     private Date modified;
     private List<BundleHasCatalog> bundleHasCatalogs = new ArrayList<BundleHasCatalog>(0);

    public Bundle() {


        //

        //
        //this.setUid(TokenUtils.generateUid());
        //

        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

    }

	
    public Bundle(String uid, String status, Date created, Date modified) {
        this.uid = uid;
        this.status = status;
        this.created = created;
        this.modified = modified;
    }
    public Bundle(String uid, String status, Boolean visible, Date created, Date modified, List<BundleHasCatalog> bundleHasCatalogs) {
       this.uid = uid;
       this.status = status;
       this.visible = visible;
       this.created = created;
       this.modified = modified;
       this.bundleHasCatalogs = bundleHasCatalogs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="uid", unique=true, nullable=false)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
   @OneToMany(fetch=FetchType.LAZY, mappedBy="bundle")
   @Cascade(value=CascadeType.ALL)                    
   @Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="Bundle.BundleHasCatalogs")
   @Fetch(value=FetchMode.SUBSELECT)                    
    public List<BundleHasCatalog> getBundleHasCatalogs() {
        return this.bundleHasCatalogs;
    }
    
    public void setBundleHasCatalogs(List<BundleHasCatalog> bundleHasCatalogs) {
        this.bundleHasCatalogs = bundleHasCatalogs;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(Bundle o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(Bundle o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
