package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * BundleHasCatalog generated by hbm
 */
@Entity
@EntityListeners(value={
BundleHasCatalog.LastUpdateListener.class,
BundleHasCatalog.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="BundleHasCatalog")
@NamedQueries({
@NamedQuery(name = "BundleHasCatalog.findAll", query = "SELECT n FROM BundleHasCatalog n"),
@NamedQuery(name = "BundleHasCatalog.findByBundle", query = "SELECT n FROM BundleHasCatalog n WHERE n.bundle = :bundle"),
@NamedQuery(name = "BundleHasCatalog.findByCreated", query = "SELECT n FROM BundleHasCatalog n WHERE n.created = :created"),
@NamedQuery(name = "BundleHasCatalog.findByModified", query = "SELECT n FROM BundleHasCatalog n WHERE n.modified = :modified"),
@NamedQuery(name = "BundleHasCatalog.findByVisible", query = "SELECT n FROM BundleHasCatalog n WHERE n.visible = :visible"),
@NamedQuery(name = "BundleHasCatalog.findByStatus", query = "SELECT n FROM BundleHasCatalog n WHERE n.status = :status"),
@NamedQuery(name = "BundleHasCatalog.findByUid", query = "SELECT n FROM BundleHasCatalog n WHERE n.uid = :uid"),
@NamedQuery(name = "BundleHasCatalog.findByCatalogid", query = "SELECT n FROM BundleHasCatalog n WHERE n.catalogid = :catalogid"),
})
@Table(name="bundle_has_catalog"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class BundleHasCatalog  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "BundleHasCatalog.findById";
        public static final String FINDBYBUNDLE = "BundleHasCatalog.findByBundle";
        public static final String FINDBYCREATED = "BundleHasCatalog.findByCreated";
        public static final String FINDBYMODIFIED = "BundleHasCatalog.findByModified";
        public static final String FINDBYVISIBLE = "BundleHasCatalog.findByVisible";
        public static final String FINDBYSTATUS = "BundleHasCatalog.findByStatus";
        public static final String FINDBYUID = "BundleHasCatalog.findByUid";
        public static final String FINDBYCATALOGID = "BundleHasCatalog.findByCatalogid";
    }




     private Integer id;
     private Bundle bundle;
     private Date created;
     private Date modified;
     private Boolean visible;
     private String status;
     private String uid;
     private int catalogid;

    public BundleHasCatalog() {


        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //

        //

    }

	
    public BundleHasCatalog(Bundle bundle, Date created, Date modified, String uid, int catalogid) {
        this.bundle = bundle;
        this.created = created;
        this.modified = modified;
        this.uid = uid;
        this.catalogid = catalogid;
    }
    public BundleHasCatalog(Bundle bundle, Date created, Date modified, Boolean visible, String status, String uid, int catalogid) {
       this.bundle = bundle;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
       this.status = status;
       this.uid = uid;
       this.catalogid = catalogid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bundle_id", nullable=false)
    public Bundle getBundle() {
        return this.bundle;
    }
    
    public void setBundle(Bundle bundle) {
        this.bundle = bundle;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="uid", unique=true, nullable=false, length=45)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    
    @Column(name="catalogid", nullable=false)
    public int getCatalogid() {
        return this.catalogid;
    }
    
    public void setCatalogid(int catalogid) {
        this.catalogid = catalogid;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(BundleHasCatalog o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(BundleHasCatalog o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
