package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CatalogHasBrand generated by hbm
 */
@Entity
@EntityListeners(value={
CatalogHasBrand.LastUpdateListener.class,
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="CatalogHasBrand")
@NamedQueries({
@NamedQuery(name = "CatalogHasBrand.findAll", query = "SELECT n FROM CatalogHasBrand n"),
@NamedQuery(name = "CatalogHasBrand.findByBrand", query = "SELECT n FROM CatalogHasBrand n WHERE n.brand = :brand"),
@NamedQuery(name = "CatalogHasBrand.findByCatalog", query = "SELECT n FROM CatalogHasBrand n WHERE n.catalog = :catalog"),
@NamedQuery(name = "CatalogHasBrand.findByCreated", query = "SELECT n FROM CatalogHasBrand n WHERE n.created = :created"),
@NamedQuery(name = "CatalogHasBrand.findByModified", query = "SELECT n FROM CatalogHasBrand n WHERE n.modified = :modified"),
@NamedQuery(name = "CatalogHasBrand.findByVisible", query = "SELECT n FROM CatalogHasBrand n WHERE n.visible = :visible"),
})
@Table(name="catalog_has_brand"
/*
    ,catalog="stgdrv_2"
*/
)
public class CatalogHasBrand  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "CatalogHasBrand.findById";
        public static final String FINDBYBRAND = "CatalogHasBrand.findByBrand";
        public static final String FINDBYCATALOG = "CatalogHasBrand.findByCatalog";
        public static final String FINDBYCREATED = "CatalogHasBrand.findByCreated";
        public static final String FINDBYMODIFIED = "CatalogHasBrand.findByModified";
        public static final String FINDBYVISIBLE = "CatalogHasBrand.findByVisible";
    }




     private CatalogHasBrandId id;
     private Brand brand;
     private Catalog catalog;
     private Date created;
     private Date modified;
     private Boolean visible;

    public CatalogHasBrand() {


        //

        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

    }

	
    public CatalogHasBrand(CatalogHasBrandId id, Brand brand, Catalog catalog, Date created, Date modified) {
        this.id = id;
        this.brand = brand;
        this.catalog = catalog;
        this.created = created;
        this.modified = modified;
    }
    public CatalogHasBrand(CatalogHasBrandId id, Brand brand, Catalog catalog, Date created, Date modified, Boolean visible) {
       this.id = id;
       this.brand = brand;
       this.catalog = catalog;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="catalogId", column=@Column(name="catalog_id", nullable=false) ), 
        @AttributeOverride(name="brandId", column=@Column(name="brand_id", nullable=false) ) } )
    public CatalogHasBrandId getId() {
        return this.id;
    }
    
    public void setId(CatalogHasBrandId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brand_id", nullable=false, insertable=false, updatable=false)
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="catalog_id", nullable=false, insertable=false, updatable=false)
    public Catalog getCatalog() {
        return this.catalog;
    }
    
    public void setCatalog(Catalog catalog) {
        this.catalog = catalog;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }





    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(CatalogHasBrand o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
