package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatalogHasItemId generated by hbm
 */
@Embeddable
public class CatalogHasItemId  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYCATALOGID = "CatalogHasItemId.findByCatalogId";
        public static final String FINDBYITEMID = "CatalogHasItemId.findByItemId";
    }




     private int catalogId;
     private int itemId;

    public CatalogHasItemId() {


        //

        //

    }

    public CatalogHasItemId(int catalogId, int itemId) {
       this.catalogId = catalogId;
       this.itemId = itemId;
    }
   

    @Column(name="catalog_id", nullable=false)
    public int getCatalogId() {
        return this.catalogId;
    }
    
    public void setCatalogId(int catalogId) {
        this.catalogId = catalogId;
    }

    @Column(name="item_id", nullable=false)
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CatalogHasItemId) ) return false;
		 CatalogHasItemId castOther = ( CatalogHasItemId ) other; 
         
		 return (this.getCatalogId()==castOther.getCatalogId())
 && (this.getItemId()==castOther.getItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCatalogId();
         result = 37 * result + this.getItemId();
         return result;
   }   



}
