package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Checkin generated by hbm
 */
@Entity
@EntityListeners(value={
Checkin.LastUpdateListener.class,
Checkin.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="Checkin")
@NamedQueries({
@NamedQuery(name = "Checkin.findAll", query = "SELECT n FROM Checkin n"),
@NamedQuery(name = "Checkin.findByUid", query = "SELECT n FROM Checkin n WHERE n.uid = :uid"),
@NamedQuery(name = "Checkin.findByCreated", query = "SELECT n FROM Checkin n WHERE n.created = :created"),
@NamedQuery(name = "Checkin.findByModified", query = "SELECT n FROM Checkin n WHERE n.modified = :modified"),
@NamedQuery(name = "Checkin.findByAccountid", query = "SELECT n FROM Checkin n WHERE n.accountid = :accountid"),
@NamedQuery(name = "Checkin.findByVisible", query = "SELECT n FROM Checkin n WHERE n.visible = :visible"),
@NamedQuery(name = "Checkin.findByStatus", query = "SELECT n FROM Checkin n WHERE n.status = :status"),
})
@Table(name="checkin"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class Checkin  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "Checkin.findById";
        public static final String FINDBYUID = "Checkin.findByUid";
        public static final String FINDBYCREATED = "Checkin.findByCreated";
        public static final String FINDBYMODIFIED = "Checkin.findByModified";
        public static final String FINDBYACCOUNTID = "Checkin.findByAccountid";
        public static final String FINDBYVISIBLE = "Checkin.findByVisible";
        public static final String FINDBYSTATUS = "Checkin.findByStatus";
    }




     private Integer id;
     private String uid;
     private Date created;
     private Date modified;
     private int accountid;
     private Boolean visible;
     private String status;
     private List<EventHasCheckin> eventHasCheckins = new ArrayList<EventHasCheckin>(0);

    public Checkin() {


        //

        //
        //this.setUid(TokenUtils.generateUid());
        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //

        //

    }

	
    public Checkin(String uid, Date created, Date modified, int accountid) {
        this.uid = uid;
        this.created = created;
        this.modified = modified;
        this.accountid = accountid;
    }
    public Checkin(String uid, Date created, Date modified, int accountid, Boolean visible, String status, List<EventHasCheckin> eventHasCheckins) {
       this.uid = uid;
       this.created = created;
       this.modified = modified;
       this.accountid = accountid;
       this.visible = visible;
       this.status = status;
       this.eventHasCheckins = eventHasCheckins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="uid", unique=true, nullable=false)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="accountid", nullable=false)
    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   @OneToMany(fetch=FetchType.LAZY, mappedBy="checkin")
   @Cascade(value=CascadeType.ALL)                    
   @Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="Checkin.EventHasCheckins")
   @Fetch(value=FetchMode.SUBSELECT)                    
    public List<EventHasCheckin> getEventHasCheckins() {
        return this.eventHasCheckins;
    }
    
    public void setEventHasCheckins(List<EventHasCheckin> eventHasCheckins) {
        this.eventHasCheckins = eventHasCheckins;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(Checkin o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(Checkin o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
