package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * EventImage generated by hbm
 */
@Entity
@EntityListeners(value={
EventImage.LastUpdateListener.class,
EventImage.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventImage")
@NamedQueries({
@NamedQuery(name = "EventImage.findAll", query = "SELECT n FROM EventImage n"),
@NamedQuery(name = "EventImage.findByEvent", query = "SELECT n FROM EventImage n WHERE n.event = :event"),
@NamedQuery(name = "EventImage.findByUid", query = "SELECT n FROM EventImage n WHERE n.uid = :uid"),
@NamedQuery(name = "EventImage.findByCreated", query = "SELECT n FROM EventImage n WHERE n.created = :created"),
@NamedQuery(name = "EventImage.findByModified", query = "SELECT n FROM EventImage n WHERE n.modified = :modified"),
@NamedQuery(name = "EventImage.findByImage", query = "SELECT n FROM EventImage n WHERE n.image = :image"),
@NamedQuery(name = "EventImage.findByTaxonomy", query = "SELECT n FROM EventImage n WHERE n.taxonomy = :taxonomy"),
})
@Table(name="event_image"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class EventImage  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventImage.findById";
        public static final String FINDBYEVENT = "EventImage.findByEvent";
        public static final String FINDBYUID = "EventImage.findByUid";
        public static final String FINDBYCREATED = "EventImage.findByCreated";
        public static final String FINDBYMODIFIED = "EventImage.findByModified";
        public static final String FINDBYIMAGE = "EventImage.findByImage";
        public static final String FINDBYTAXONOMY = "EventImage.findByTaxonomy";
    }




     private Integer id;
     private Event event;
     private String uid;
     private Date created;
     private Date modified;
     private String image;
     private String taxonomy;

    public EventImage() {


        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

    }

    public EventImage(Event event, String uid, Date created, Date modified, String image, String taxonomy) {
       this.event = event;
       this.uid = uid;
       this.created = created;
       this.modified = modified;
       this.image = image;
       this.taxonomy = taxonomy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    
    @Column(name="uid", unique=true, nullable=false)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="image", nullable=false, length=65535)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    
    @Column(name="taxonomy", nullable=false, length=45)
    public String getTaxonomy() {
        return this.taxonomy;
    }
    
    public void setTaxonomy(String taxonomy) {
        this.taxonomy = taxonomy;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(EventImage o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(EventImage o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
