package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * EventTicket generated by hbm
 */
@Entity
@EntityListeners(value={
EventTicket.LastUpdateListener.class,
EventTicket.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventTicket")
@NamedQueries({
@NamedQuery(name = "EventTicket.findAll", query = "SELECT n FROM EventTicket n"),
@NamedQuery(name = "EventTicket.findByUid", query = "SELECT n FROM EventTicket n WHERE n.uid = :uid"),
@NamedQuery(name = "EventTicket.findByCreated", query = "SELECT n FROM EventTicket n WHERE n.created = :created"),
@NamedQuery(name = "EventTicket.findByModified", query = "SELECT n FROM EventTicket n WHERE n.modified = :modified"),
@NamedQuery(name = "EventTicket.findByVisible", query = "SELECT n FROM EventTicket n WHERE n.visible = :visible"),
@NamedQuery(name = "EventTicket.findByStatus", query = "SELECT n FROM EventTicket n WHERE n.status = :status"),
@NamedQuery(name = "EventTicket.findByName", query = "SELECT n FROM EventTicket n WHERE n.name = :name"),
@NamedQuery(name = "EventTicket.findByDescription", query = "SELECT n FROM EventTicket n WHERE n.description = :description"),
})
@Table(name="event_ticket"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class EventTicket  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventTicket.findById";
        public static final String FINDBYUID = "EventTicket.findByUid";
        public static final String FINDBYCREATED = "EventTicket.findByCreated";
        public static final String FINDBYMODIFIED = "EventTicket.findByModified";
        public static final String FINDBYVISIBLE = "EventTicket.findByVisible";
        public static final String FINDBYSTATUS = "EventTicket.findByStatus";
        public static final String FINDBYNAME = "EventTicket.findByName";
        public static final String FINDBYDESCRIPTION = "EventTicket.findByDescription";
    }




     private Integer id;
     private String uid;
     private Date created;
     private Date modified;
     private Boolean visible;
     private String status;
     private String name;
     private String description;
     private List<EventHasBuyer> eventHasBuyers = new ArrayList<EventHasBuyer>(0);
     private List<TicketImage> ticketImages = new ArrayList<TicketImage>(0);

    public EventTicket() {


        //

        //
        //this.setUid(TokenUtils.generateUid());
        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //

        //

        //

        //

    }

	
    public EventTicket(String uid, Date created, Date modified) {
        this.uid = uid;
        this.created = created;
        this.modified = modified;
    }
    public EventTicket(String uid, Date created, Date modified, Boolean visible, String status, String name, String description, List<EventHasBuyer> eventHasBuyers, List<TicketImage> ticketImages) {
       this.uid = uid;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
       this.status = status;
       this.name = name;
       this.description = description;
       this.eventHasBuyers = eventHasBuyers;
       this.ticketImages = ticketImages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="uid", unique=true, nullable=false)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="name", length=2555)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   @OneToMany(fetch=FetchType.LAZY, mappedBy="eventTicket")
   @Cascade(value=CascadeType.ALL)                    
   @Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventTicket.EventHasBuyers")
   @Fetch(value=FetchMode.SUBSELECT)                    
    public List<EventHasBuyer> getEventHasBuyers() {
        return this.eventHasBuyers;
    }
    
    public void setEventHasBuyers(List<EventHasBuyer> eventHasBuyers) {
        this.eventHasBuyers = eventHasBuyers;
    }
   @OneToMany(fetch=FetchType.LAZY, mappedBy="eventTicket")
   @Cascade(value=CascadeType.ALL)                    
   @Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventTicket.TicketImages")
   @Fetch(value=FetchMode.SUBSELECT)                    
    public List<TicketImage> getTicketImages() {
        return this.ticketImages;
    }
    
    public void setTicketImages(List<TicketImage> ticketImages) {
        this.ticketImages = ticketImages;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(EventTicket o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(EventTicket o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
