package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * EventHasCatalog generated by hbm
 */
@Entity
@EntityListeners(value={
EventHasCatalog.LastUpdateListener.class,
EventHasCatalog.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventHasCatalog")
@NamedQueries({
@NamedQuery(name = "EventHasCatalog.findAll", query = "SELECT n FROM EventHasCatalog n"),
@NamedQuery(name = "EventHasCatalog.findByEvent", query = "SELECT n FROM EventHasCatalog n WHERE n.event = :event"),
@NamedQuery(name = "EventHasCatalog.findByCreated", query = "SELECT n FROM EventHasCatalog n WHERE n.created = :created"),
@NamedQuery(name = "EventHasCatalog.findByModified", query = "SELECT n FROM EventHasCatalog n WHERE n.modified = :modified"),
@NamedQuery(name = "EventHasCatalog.findByVisible", query = "SELECT n FROM EventHasCatalog n WHERE n.visible = :visible"),
@NamedQuery(name = "EventHasCatalog.findByStatus", query = "SELECT n FROM EventHasCatalog n WHERE n.status = :status"),
@NamedQuery(name = "EventHasCatalog.findByUid", query = "SELECT n FROM EventHasCatalog n WHERE n.uid = :uid"),
@NamedQuery(name = "EventHasCatalog.findByCatalogid", query = "SELECT n FROM EventHasCatalog n WHERE n.catalogid = :catalogid"),
})
@Table(name="event_has_catalog"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class EventHasCatalog  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventHasCatalog.findById";
        public static final String FINDBYEVENT = "EventHasCatalog.findByEvent";
        public static final String FINDBYCREATED = "EventHasCatalog.findByCreated";
        public static final String FINDBYMODIFIED = "EventHasCatalog.findByModified";
        public static final String FINDBYVISIBLE = "EventHasCatalog.findByVisible";
        public static final String FINDBYSTATUS = "EventHasCatalog.findByStatus";
        public static final String FINDBYUID = "EventHasCatalog.findByUid";
        public static final String FINDBYCATALOGID = "EventHasCatalog.findByCatalogid";
    }




     private Integer id;
     private Event event;
     private Date created;
     private Date modified;
     private Boolean visible;
     private String status;
     private String uid;
     private Integer catalogid;

    public EventHasCatalog() {


        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //

        //

    }

	
    public EventHasCatalog(Event event, Date created, Date modified, String uid) {
        this.event = event;
        this.created = created;
        this.modified = modified;
        this.uid = uid;
    }
    public EventHasCatalog(Event event, Date created, Date modified, Boolean visible, String status, String uid, Integer catalogid) {
       this.event = event;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
       this.status = status;
       this.uid = uid;
       this.catalogid = catalogid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="uid", unique=true, nullable=false, length=45)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    
    @Column(name="catalogid")
    public Integer getCatalogid() {
        return this.catalogid;
    }
    
    public void setCatalogid(Integer catalogid) {
        this.catalogid = catalogid;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(EventHasCatalog o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(EventHasCatalog o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
