package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * EventHasFellowship generated by hbm
 */
@Entity
@EntityListeners(value={
EventHasFellowship.LastUpdateListener.class,
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventHasFellowship")
@NamedQueries({
@NamedQuery(name = "EventHasFellowship.findAll", query = "SELECT n FROM EventHasFellowship n"),
@NamedQuery(name = "EventHasFellowship.findByEvent", query = "SELECT n FROM EventHasFellowship n WHERE n.event = :event"),
@NamedQuery(name = "EventHasFellowship.findByFellowship", query = "SELECT n FROM EventHasFellowship n WHERE n.fellowship = :fellowship"),
@NamedQuery(name = "EventHasFellowship.findByCreated", query = "SELECT n FROM EventHasFellowship n WHERE n.created = :created"),
@NamedQuery(name = "EventHasFellowship.findByModified", query = "SELECT n FROM EventHasFellowship n WHERE n.modified = :modified"),
@NamedQuery(name = "EventHasFellowship.findByVisible", query = "SELECT n FROM EventHasFellowship n WHERE n.visible = :visible"),
})
@Table(name="event_has_fellowship"
/*
    ,catalog="stgdrv_2"
*/
)
public class EventHasFellowship  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventHasFellowship.findById";
        public static final String FINDBYEVENT = "EventHasFellowship.findByEvent";
        public static final String FINDBYFELLOWSHIP = "EventHasFellowship.findByFellowship";
        public static final String FINDBYCREATED = "EventHasFellowship.findByCreated";
        public static final String FINDBYMODIFIED = "EventHasFellowship.findByModified";
        public static final String FINDBYVISIBLE = "EventHasFellowship.findByVisible";
    }




     private EventHasFellowshipId id;
     private Event event;
     private Fellowship fellowship;
     private Date created;
     private Date modified;
     private Boolean visible;

    public EventHasFellowship() {


        //

        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

    }

	
    public EventHasFellowship(EventHasFellowshipId id, Event event, Fellowship fellowship, Date created, Date modified) {
        this.id = id;
        this.event = event;
        this.fellowship = fellowship;
        this.created = created;
        this.modified = modified;
    }
    public EventHasFellowship(EventHasFellowshipId id, Event event, Fellowship fellowship, Date created, Date modified, Boolean visible) {
       this.id = id;
       this.event = event;
       this.fellowship = fellowship;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="eventId", column=@Column(name="event_id", nullable=false) ), 
        @AttributeOverride(name="fellowshipId", column=@Column(name="fellowship_id", nullable=false) ) } )
    public EventHasFellowshipId getId() {
        return this.id;
    }
    
    public void setId(EventHasFellowshipId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false, insertable=false, updatable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fellowship_id", nullable=false, insertable=false, updatable=false)
    public Fellowship getFellowship() {
        return this.fellowship;
    }
    
    public void setFellowship(Fellowship fellowship) {
        this.fellowship = fellowship;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }





    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(EventHasFellowship o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
