package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * EventHasBuyer generated by hbm
 */
@Entity
@EntityListeners(value={
EventHasBuyer.LastUpdateListener.class,
EventHasBuyer.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventHasBuyer")
@NamedQueries({
@NamedQuery(name = "EventHasBuyer.findAll", query = "SELECT n FROM EventHasBuyer n"),
@NamedQuery(name = "EventHasBuyer.findByEventTicket", query = "SELECT n FROM EventHasBuyer n WHERE n.eventTicket = :eventTicket"),
@NamedQuery(name = "EventHasBuyer.findByEvent", query = "SELECT n FROM EventHasBuyer n WHERE n.event = :event"),
@NamedQuery(name = "EventHasBuyer.findByCreated", query = "SELECT n FROM EventHasBuyer n WHERE n.created = :created"),
@NamedQuery(name = "EventHasBuyer.findByModified", query = "SELECT n FROM EventHasBuyer n WHERE n.modified = :modified"),
@NamedQuery(name = "EventHasBuyer.findByVisible", query = "SELECT n FROM EventHasBuyer n WHERE n.visible = :visible"),
@NamedQuery(name = "EventHasBuyer.findByStatus", query = "SELECT n FROM EventHasBuyer n WHERE n.status = :status"),
@NamedQuery(name = "EventHasBuyer.findByAccountid", query = "SELECT n FROM EventHasBuyer n WHERE n.accountid = :accountid"),
@NamedQuery(name = "EventHasBuyer.findByUid", query = "SELECT n FROM EventHasBuyer n WHERE n.uid = :uid"),
})
@Table(name="event_has_buyer"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class EventHasBuyer  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventHasBuyer.findById";
        public static final String FINDBYEVENTTICKET = "EventHasBuyer.findByEventTicket";
        public static final String FINDBYEVENT = "EventHasBuyer.findByEvent";
        public static final String FINDBYCREATED = "EventHasBuyer.findByCreated";
        public static final String FINDBYMODIFIED = "EventHasBuyer.findByModified";
        public static final String FINDBYVISIBLE = "EventHasBuyer.findByVisible";
        public static final String FINDBYSTATUS = "EventHasBuyer.findByStatus";
        public static final String FINDBYACCOUNTID = "EventHasBuyer.findByAccountid";
        public static final String FINDBYUID = "EventHasBuyer.findByUid";
    }




     private EventHasBuyerId id;
     private EventTicket eventTicket;
     private Event event;
     private Date created;
     private Date modified;
     private Boolean visible;
     private String status;
     private int accountid;
     private String uid;

    public EventHasBuyer() {


        //

        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //

    }

	
    public EventHasBuyer(EventHasBuyerId id, EventTicket eventTicket, Event event, Date created, Date modified, int accountid, String uid) {
        this.id = id;
        this.eventTicket = eventTicket;
        this.event = event;
        this.created = created;
        this.modified = modified;
        this.accountid = accountid;
        this.uid = uid;
    }
    public EventHasBuyer(EventHasBuyerId id, EventTicket eventTicket, Event event, Date created, Date modified, Boolean visible, String status, int accountid, String uid) {
       this.id = id;
       this.eventTicket = eventTicket;
       this.event = event;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
       this.status = status;
       this.accountid = accountid;
       this.uid = uid;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="eventTicketId", column=@Column(name="event_ticket_id", nullable=false) ) } )
    public EventHasBuyerId getId() {
        return this.id;
    }
    
    public void setId(EventHasBuyerId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_ticket_id", nullable=false, insertable=false, updatable=false)
    public EventTicket getEventTicket() {
        return this.eventTicket;
    }
    
    public void setEventTicket(EventTicket eventTicket) {
        this.eventTicket = eventTicket;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="accountid", nullable=false)
    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
    
    @Column(name="uid", unique=true, nullable=false, length=45)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(EventHasBuyer o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(EventHasBuyer o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
