package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * EventHasAction generated by hbm
 */
@Entity
@EntityListeners(value={
EventHasAction.LastUpdateListener.class,
EventHasAction.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventHasAction")
@NamedQueries({
@NamedQuery(name = "EventHasAction.findAll", query = "SELECT n FROM EventHasAction n"),
@NamedQuery(name = "EventHasAction.findByEvent", query = "SELECT n FROM EventHasAction n WHERE n.event = :event"),
@NamedQuery(name = "EventHasAction.findByCreated", query = "SELECT n FROM EventHasAction n WHERE n.created = :created"),
@NamedQuery(name = "EventHasAction.findByModified", query = "SELECT n FROM EventHasAction n WHERE n.modified = :modified"),
@NamedQuery(name = "EventHasAction.findByVisible", query = "SELECT n FROM EventHasAction n WHERE n.visible = :visible"),
@NamedQuery(name = "EventHasAction.findByStatus", query = "SELECT n FROM EventHasAction n WHERE n.status = :status"),
@NamedQuery(name = "EventHasAction.findByAccountid", query = "SELECT n FROM EventHasAction n WHERE n.accountid = :accountid"),
@NamedQuery(name = "EventHasAction.findByUid", query = "SELECT n FROM EventHasAction n WHERE n.uid = :uid"),
@NamedQuery(name = "EventHasAction.findByImage", query = "SELECT n FROM EventHasAction n WHERE n.image = :image"),
@NamedQuery(name = "EventHasAction.findByTaxonomy", query = "SELECT n FROM EventHasAction n WHERE n.taxonomy = :taxonomy"),
@NamedQuery(name = "EventHasAction.findByContent", query = "SELECT n FROM EventHasAction n WHERE n.content = :content"),
})
@Table(name="event_has_action"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class EventHasAction  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventHasAction.findById";
        public static final String FINDBYEVENT = "EventHasAction.findByEvent";
        public static final String FINDBYCREATED = "EventHasAction.findByCreated";
        public static final String FINDBYMODIFIED = "EventHasAction.findByModified";
        public static final String FINDBYVISIBLE = "EventHasAction.findByVisible";
        public static final String FINDBYSTATUS = "EventHasAction.findByStatus";
        public static final String FINDBYACCOUNTID = "EventHasAction.findByAccountid";
        public static final String FINDBYUID = "EventHasAction.findByUid";
        public static final String FINDBYIMAGE = "EventHasAction.findByImage";
        public static final String FINDBYTAXONOMY = "EventHasAction.findByTaxonomy";
        public static final String FINDBYCONTENT = "EventHasAction.findByContent";
    }




     private Integer id;
     private Event event;
     private Date created;
     private Date modified;
     private Boolean visible;
     private String status;
     private int accountid;
     private String uid;
     private String image;
     private String taxonomy;
     private String content;

    public EventHasAction() {


        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //

        //

        //

        //

    }

	
    public EventHasAction(Event event, Date created, Date modified, int accountid, String uid, String taxonomy) {
        this.event = event;
        this.created = created;
        this.modified = modified;
        this.accountid = accountid;
        this.uid = uid;
        this.taxonomy = taxonomy;
    }
    public EventHasAction(Event event, Date created, Date modified, Boolean visible, String status, int accountid, String uid, String image, String taxonomy, String content) {
       this.event = event;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
       this.status = status;
       this.accountid = accountid;
       this.uid = uid;
       this.image = image;
       this.taxonomy = taxonomy;
       this.content = content;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="accountid", nullable=false)
    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
    
    @Column(name="uid", unique=true, nullable=false, length=45)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    
    @Column(name="image", length=65535)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    
    @Column(name="taxonomy", nullable=false, length=20)
    public String getTaxonomy() {
        return this.taxonomy;
    }
    
    public void setTaxonomy(String taxonomy) {
        this.taxonomy = taxonomy;
    }
    
    @Column(name="content", length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(EventHasAction o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(EventHasAction o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
