package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * EventHasCheckin generated by hbm
 */
@Entity
@EntityListeners(value={
EventHasCheckin.LastUpdateListener.class,
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="EventHasCheckin")
@NamedQueries({
@NamedQuery(name = "EventHasCheckin.findAll", query = "SELECT n FROM EventHasCheckin n"),
@NamedQuery(name = "EventHasCheckin.findByCheckin", query = "SELECT n FROM EventHasCheckin n WHERE n.checkin = :checkin"),
@NamedQuery(name = "EventHasCheckin.findByEvent", query = "SELECT n FROM EventHasCheckin n WHERE n.event = :event"),
@NamedQuery(name = "EventHasCheckin.findByCreated", query = "SELECT n FROM EventHasCheckin n WHERE n.created = :created"),
@NamedQuery(name = "EventHasCheckin.findByModified", query = "SELECT n FROM EventHasCheckin n WHERE n.modified = :modified"),
@NamedQuery(name = "EventHasCheckin.findByVisible", query = "SELECT n FROM EventHasCheckin n WHERE n.visible = :visible"),
})
@Table(name="event_has_checkin"
/*
    ,catalog="stgdrv_2"
*/
)
public class EventHasCheckin  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventHasCheckin.findById";
        public static final String FINDBYCHECKIN = "EventHasCheckin.findByCheckin";
        public static final String FINDBYEVENT = "EventHasCheckin.findByEvent";
        public static final String FINDBYCREATED = "EventHasCheckin.findByCreated";
        public static final String FINDBYMODIFIED = "EventHasCheckin.findByModified";
        public static final String FINDBYVISIBLE = "EventHasCheckin.findByVisible";
    }




     private EventHasCheckinId id;
     private Checkin checkin;
     private Event event;
     private Date created;
     private Date modified;
     private Boolean visible;

    public EventHasCheckin() {


        //

        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

    }

	
    public EventHasCheckin(EventHasCheckinId id, Checkin checkin, Event event, Date created, Date modified) {
        this.id = id;
        this.checkin = checkin;
        this.event = event;
        this.created = created;
        this.modified = modified;
    }
    public EventHasCheckin(EventHasCheckinId id, Checkin checkin, Event event, Date created, Date modified, Boolean visible) {
       this.id = id;
       this.checkin = checkin;
       this.event = event;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="checkinId", column=@Column(name="checkin_id", nullable=false) ), 
        @AttributeOverride(name="eventId", column=@Column(name="event_id", nullable=false) ) } )
    public EventHasCheckinId getId() {
        return this.id;
    }
    
    public void setId(EventHasCheckinId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="checkin_id", nullable=false, insertable=false, updatable=false)
    public Checkin getCheckin() {
        return this.checkin;
    }
    
    public void setCheckin(Checkin checkin) {
        this.checkin = checkin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false, insertable=false, updatable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }





    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(EventHasCheckin o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
