package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventHasBuyerId generated by hbm
 */
@Embeddable
public class EventHasBuyerId  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "EventHasBuyerId.findById";
        public static final String FINDBYEVENTTICKETID = "EventHasBuyerId.findByEventTicketId";
    }




     private int id;
     private int eventTicketId;

    public EventHasBuyerId() {


        //

        //

    }

    public EventHasBuyerId(int id, int eventTicketId) {
       this.id = id;
       this.eventTicketId = eventTicketId;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="event_ticket_id", nullable=false)
    public int getEventTicketId() {
        return this.eventTicketId;
    }
    
    public void setEventTicketId(int eventTicketId) {
        this.eventTicketId = eventTicketId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventHasBuyerId) ) return false;
		 EventHasBuyerId castOther = ( EventHasBuyerId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getEventTicketId()==castOther.getEventTicketId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getEventTicketId();
         return result;
   }   



}
