package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * ItemCategory generated by hbm
 */
@Entity
@EntityListeners(value={
ItemCategory.LastUpdateListener.class,
ItemCategory.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="ItemCategory")
@NamedQueries({
@NamedQuery(name = "ItemCategory.findAll", query = "SELECT n FROM ItemCategory n"),
@NamedQuery(name = "ItemCategory.findByItemFamily", query = "SELECT n FROM ItemCategory n WHERE n.itemFamily = :itemFamily"),
@NamedQuery(name = "ItemCategory.findByUid", query = "SELECT n FROM ItemCategory n WHERE n.uid = :uid"),
@NamedQuery(name = "ItemCategory.findByCreated", query = "SELECT n FROM ItemCategory n WHERE n.created = :created"),
@NamedQuery(name = "ItemCategory.findByModified", query = "SELECT n FROM ItemCategory n WHERE n.modified = :modified"),
@NamedQuery(name = "ItemCategory.findByName", query = "SELECT n FROM ItemCategory n WHERE n.name = :name"),
@NamedQuery(name = "ItemCategory.findByVisible", query = "SELECT n FROM ItemCategory n WHERE n.visible = :visible"),
@NamedQuery(name = "ItemCategory.findByDescription", query = "SELECT n FROM ItemCategory n WHERE n.description = :description"),
@NamedQuery(name = "ItemCategory.findByPosition", query = "SELECT n FROM ItemCategory n WHERE n.position = :position"),
@NamedQuery(name = "ItemCategory.findByTag", query = "SELECT n FROM ItemCategory n WHERE n.tag = :tag"),
})
@Table(name="item_category"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class ItemCategory  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "ItemCategory.findById";
        public static final String FINDBYITEMFAMILY = "ItemCategory.findByItemFamily";
        public static final String FINDBYUID = "ItemCategory.findByUid";
        public static final String FINDBYCREATED = "ItemCategory.findByCreated";
        public static final String FINDBYMODIFIED = "ItemCategory.findByModified";
        public static final String FINDBYNAME = "ItemCategory.findByName";
        public static final String FINDBYVISIBLE = "ItemCategory.findByVisible";
        public static final String FINDBYDESCRIPTION = "ItemCategory.findByDescription";
        public static final String FINDBYPOSITION = "ItemCategory.findByPosition";
        public static final String FINDBYTAG = "ItemCategory.findByTag";
    }




     private Integer id;
     private ItemFamily itemFamily;
     private String uid;
     private Date created;
     private Date modified;
     private String name;
     private Boolean visible;
     private String description;
     private Integer position;
     private String tag;
     private List<ItemHasCategory> itemHasCategories = new ArrayList<ItemHasCategory>(0);

    public ItemCategory() {


        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //

        //

        //

        //

        //

    }

	
    public ItemCategory(ItemFamily itemFamily, String uid, Date created, Date modified, String name) {
        this.itemFamily = itemFamily;
        this.uid = uid;
        this.created = created;
        this.modified = modified;
        this.name = name;
    }
    public ItemCategory(ItemFamily itemFamily, String uid, Date created, Date modified, String name, Boolean visible, String description, Integer position, String tag, List<ItemHasCategory> itemHasCategories) {
       this.itemFamily = itemFamily;
       this.uid = uid;
       this.created = created;
       this.modified = modified;
       this.name = name;
       this.visible = visible;
       this.description = description;
       this.position = position;
       this.tag = tag;
       this.itemHasCategories = itemHasCategories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_family_id", nullable=false)
    public ItemFamily getItemFamily() {
        return this.itemFamily;
    }
    
    public void setItemFamily(ItemFamily itemFamily) {
        this.itemFamily = itemFamily;
    }
    
    @Column(name="uid", unique=true, nullable=false, length=100)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
    
    @Column(name="tag", length=45)
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
   @OneToMany(fetch=FetchType.LAZY, mappedBy="itemCategory")
   @Cascade(value=CascadeType.ALL)                    
   @Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="ItemCategory.ItemHasCategories")
   @Fetch(value=FetchMode.SUBSELECT)                    
    public List<ItemHasCategory> getItemHasCategories() {
        return this.itemHasCategories;
    }
    
    public void setItemHasCategories(List<ItemHasCategory> itemHasCategories) {
        this.itemHasCategories = itemHasCategories;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(ItemCategory o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(ItemCategory o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
