package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ItemHasColor generated by hbm
 */
@Entity
@EntityListeners(value={
ItemHasColor.LastUpdateListener.class,
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="ItemHasColor")
@NamedQueries({
@NamedQuery(name = "ItemHasColor.findAll", query = "SELECT n FROM ItemHasColor n"),
@NamedQuery(name = "ItemHasColor.findByItem", query = "SELECT n FROM ItemHasColor n WHERE n.item = :item"),
@NamedQuery(name = "ItemHasColor.findByColor", query = "SELECT n FROM ItemHasColor n WHERE n.color = :color"),
@NamedQuery(name = "ItemHasColor.findByCreated", query = "SELECT n FROM ItemHasColor n WHERE n.created = :created"),
@NamedQuery(name = "ItemHasColor.findByModified", query = "SELECT n FROM ItemHasColor n WHERE n.modified = :modified"),
@NamedQuery(name = "ItemHasColor.findByVisible", query = "SELECT n FROM ItemHasColor n WHERE n.visible = :visible"),
})
@Table(name="item_has_color"
/*
    ,catalog="stgdrv_2"
*/
)
public class ItemHasColor  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "ItemHasColor.findById";
        public static final String FINDBYITEM = "ItemHasColor.findByItem";
        public static final String FINDBYCOLOR = "ItemHasColor.findByColor";
        public static final String FINDBYCREATED = "ItemHasColor.findByCreated";
        public static final String FINDBYMODIFIED = "ItemHasColor.findByModified";
        public static final String FINDBYVISIBLE = "ItemHasColor.findByVisible";
    }




     private ItemHasColorId id;
     private Item item;
     private Color color;
     private Date created;
     private Date modified;
     private Boolean visible;

    public ItemHasColor() {


        //

        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

    }

	
    public ItemHasColor(ItemHasColorId id, Item item, Color color, Date created, Date modified) {
        this.id = id;
        this.item = item;
        this.color = color;
        this.created = created;
        this.modified = modified;
    }
    public ItemHasColor(ItemHasColorId id, Item item, Color color, Date created, Date modified, Boolean visible) {
       this.id = id;
       this.item = item;
       this.color = color;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="itemId", column=@Column(name="item_id", nullable=false) ), 
        @AttributeOverride(name="colorId", column=@Column(name="color_id", nullable=false) ) } )
    public ItemHasColorId getId() {
        return this.id;
    }
    
    public void setId(ItemHasColorId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="color_id", nullable=false, insertable=false, updatable=false)
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }





    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(ItemHasColor o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
