package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import com.justbit.commons.TokenUtils;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ItemHasCategory generated by hbm
 */
@Entity
@EntityListeners(value={
ItemHasCategory.LastUpdateListener.class,
ItemHasCategory.UidListener.class
})
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL, region="ItemHasCategory")
@NamedQueries({
@NamedQuery(name = "ItemHasCategory.findAll", query = "SELECT n FROM ItemHasCategory n"),
@NamedQuery(name = "ItemHasCategory.findByItem", query = "SELECT n FROM ItemHasCategory n WHERE n.item = :item"),
@NamedQuery(name = "ItemHasCategory.findByItemCategory", query = "SELECT n FROM ItemHasCategory n WHERE n.itemCategory = :itemCategory"),
@NamedQuery(name = "ItemHasCategory.findByCreated", query = "SELECT n FROM ItemHasCategory n WHERE n.created = :created"),
@NamedQuery(name = "ItemHasCategory.findByModified", query = "SELECT n FROM ItemHasCategory n WHERE n.modified = :modified"),
@NamedQuery(name = "ItemHasCategory.findByVisible", query = "SELECT n FROM ItemHasCategory n WHERE n.visible = :visible"),
@NamedQuery(name = "ItemHasCategory.findByUid", query = "SELECT n FROM ItemHasCategory n WHERE n.uid = :uid"),
})
@Table(name="item_has_category"
/*
    ,catalog="stgdrv_2"
*/
    , uniqueConstraints = @UniqueConstraint(columnNames="uid") 
)
public class ItemHasCategory  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "ItemHasCategory.findById";
        public static final String FINDBYITEM = "ItemHasCategory.findByItem";
        public static final String FINDBYITEMCATEGORY = "ItemHasCategory.findByItemCategory";
        public static final String FINDBYCREATED = "ItemHasCategory.findByCreated";
        public static final String FINDBYMODIFIED = "ItemHasCategory.findByModified";
        public static final String FINDBYVISIBLE = "ItemHasCategory.findByVisible";
        public static final String FINDBYUID = "ItemHasCategory.findByUid";
    }




     private Integer id;
     private Item item;
     private ItemCategory itemCategory;
     private Date created;
     private Date modified;
     private Boolean visible;
     private String uid;

    public ItemHasCategory() {


        //

        //

        //
        this.setCreated(new Date());
        this.setModified(new Date());

        //

        //

        //

        //
        //this.setUid(TokenUtils.generateUid());
        //

    }

	
    public ItemHasCategory(Item item, ItemCategory itemCategory, Date created, Date modified, String uid) {
        this.item = item;
        this.itemCategory = itemCategory;
        this.created = created;
        this.modified = modified;
        this.uid = uid;
    }
    public ItemHasCategory(Item item, ItemCategory itemCategory, Date created, Date modified, Boolean visible, String uid) {
       this.item = item;
       this.itemCategory = itemCategory;
       this.created = created;
       this.modified = modified;
       this.visible = visible;
       this.uid = uid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_category_id", nullable=false)
    public ItemCategory getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(ItemCategory itemCategory) {
        this.itemCategory = itemCategory;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=0)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=0)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="visible")
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    
    @Column(name="uid", unique=true, nullable=false, length=100)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }




    public class UidListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setUid(ItemHasCategory o) {
            if (o.getUid() == null) {
                o.setUid(TokenUtils.generateUid());
            }
        }
    }

    public class LastUpdateListener {
        /**
         * automatic property set before any database persistence
         */
        @PreUpdate
        @PrePersist
        public void setModified(ItemHasCategory o) {
            if (o.getCreated() == null) {
                o.setCreated(new Date());
            }
            o.setModified(new Date());
        }
    }
}
