package com.stagedriving.modules.commons.ds.entities;
// Generated 12-giu-2020 14.48.36 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RideHasActionId generated by hbm
 */
@Embeddable
public class RideHasActionId  implements java.io.Serializable {


    public class NamedQueries {
        public static final String FINDBYID = "RideHasActionId.findById";
        public static final String FINDBYRIDEID = "RideHasActionId.findByRideId";
    }




     private int id;
     private int rideId;

    public RideHasActionId() {


        //

        //

    }

    public RideHasActionId(int id, int rideId) {
       this.id = id;
       this.rideId = rideId;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="ride_id", nullable=false)
    public int getRideId() {
        return this.rideId;
    }
    
    public void setRideId(int rideId) {
        this.rideId = rideId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RideHasActionId) ) return false;
		 RideHasActionId castOther = ( RideHasActionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getRideId()==castOther.getRideId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getRideId();
         return result;
   }   



}
