apiVersion: v1
kind: Service
metadata:
  labels:
    name: stagedriving-staging-be-lb
  name: stagedriving-staging-be-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: standard
      targetPort: 8080
      protocol: TCP
    - port: 9900
      name: admin
      targetPort: 9900
      protocol: TCP
  selector:
    app: stagedriving-staging-be

