apiVersion: v1
kind: ReplicationController
metadata:
  name: ofs-staging-web
  labels:
    name: ofs-staging-web
spec:
  replicas: 1
  selector:
    name: ofs-staging-web
  template:
    metadata:
      labels:
        name: ofs-staging-web
    spec:
      containers:
      - image: eu.gcr.io/justbit-cloud/ofs_web:ae7c1253abb1fbf000f7e515b4cc8f24a9e877c1
        name: ofs-staging-web
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 50m
        env:
        - name: ENV_MODE
          value: staging
        - name: WP_DOMAIN
          value: https://ofs.justbit.it
        - name: DB_HOSTNAME
          value: mysql1.justbit.it
        - name: DB_PASSWORD
          value: m378td76b 7b
        - name: DB_USER
          value: ofs
        - name: DB_NAME
          value: wp_ofs-stage
        - name: BUCKET_NAME
          value: jb-wp-uploads4
        - name: BUCKET_DIR
          value: ofs-stage-wp
