web:
  build: .
  ports:
   - "8989:80"
   - "9000:9000"
  volumes:
   - .:/usr/share/nginx/www/
  links:
   - mysql:mysql
  environment:
   - ENV_MODE=development
   - WP_DOMAIN=http://sd.localhost:8989
   #https://stagedriving.com/wp
   - DB_HOSTNAME=mysql
   - DB_PASSWORD=admin
   - DB_USER=root
   - DB_NAME=wordpress_sd
   - RUN_COMPOSER=1
   #- DEBUG_HOST="192.168.10.46"
   #- BUCKET_NAME=jb-wp-uploads
   #- BUCKET_DIR=selphiegum-web
mysql:
  image: mysql:5.7
  ports:
   - "3333:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin
