/**
 * Stage Driving API
 * API specifications
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventDTO } from './eventDTO';


export interface CheckinDTO {
    id?: string;
    created?: string;
    modified?: string;
    accountid?: number;
    visible?: boolean;
    status?: string;
    events?: Array<EventDTO>;
}
