/**
 * Stage Driving API
 * API specifications
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommentDTO } from './commentDTO';
import { EventDTO } from './eventDTO';
import { ItemDTO } from './itemDTO';


export interface FeedDTO {
    id?: string;
    created?: string;
    modified?: string;
    bookmark?: boolean;
    like?: boolean;
    ncomment?: number;
    nlike?: number;
    content?: string;
    event?: EventDTO;
    item?: ItemDTO;
    comments?: Array<CommentDTO>;
}
